"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { ArrowLeft, Clock3, MapPin, ShieldCheck, Users } from "lucide-react";

type Slot = { id: string; startAt: string; endAt: string; remaining: number; crowd: { label: string; color: string } };
type Item = { title: string; summary: string; description: string | null; notice: string | null; image: string | null; venue: { name: string; address: string }; slots: Slot[] };

export default function TicketDetailPage() {
  const { id } = useParams<{id:string}>(); const router=useRouter(); const [item,setItem]=useState<Item|null>(null); const [slotId,setSlotId]=useState(""); const [quantity,setQuantity]=useState(1); const [contactName,setContactName]=useState(""); const [contactPhone,setContactPhone]=useState(""); const [message,setMessage]=useState(""); const [submitting,setSubmitting]=useState(false); const [loading,setLoading]=useState(true); const [loadError,setLoadError]=useState(""); const [retry,setRetry]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/tickets/${id}`,{signal:controller.signal}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(payload.error??"票务项目加载失败");setItem(payload.item??null);setSlotId(payload.item?.slots?.[0]?.id??"")}).catch(reason=>{if(!controller.signal.aborted)setLoadError(reason instanceof Error?reason.message:"票务项目加载失败")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[id,retry]);
  async function submit(){setSubmitting(true);setMessage("");const res=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({slotId,quantity,contactName,contactPhone})});const data=await res.json();setSubmitting(false);if(res.status===401){router.push(`/login?next=/tickets/${id}`);return}if(!res.ok){setMessage(data.error??"预约失败");return}router.push("/profile/bookings");}
  if(loading) return <div className="min-h-screen bg-[#f8f3eb] py-24 text-center text-slate-500">正在加载…</div>;
  if(loadError||!item) return <div className="min-h-screen bg-[#f8f3eb] py-24 text-center"><p className="text-[#b83c2f]">{loadError||"票务项目不存在"}</p><button onClick={()=>{setLoading(true);setLoadError("");setRetry(value=>value+1)}} className="mt-4 rounded-lg bg-[#25332f] px-5 py-2 text-sm text-white">重新加载</button><Link href="/tickets" className="ml-3 text-sm text-slate-500">返回列表</Link></div>;
  return <main className="min-h-screen bg-[#f8f3eb] px-5 py-8 text-[#24332f]"><div className="mx-auto max-w-6xl"><Link href="/tickets" className="inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={16}/>返回票务列表</Link><div className="mt-6 grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="overflow-hidden rounded-3xl border border-[#e6ddd0] bg-white"><div className="h-72 bg-[#ded6ca] bg-cover bg-center" style={{backgroundImage:`url(${item.image||"/images/sanfangqixiang.jpg"})`}}/><div className="p-7"><h1 className="font-serif text-3xl">{item.title}</h1><p className="mt-3 leading-7 text-slate-600">{item.summary}</p><div className="mt-5 grid gap-3 rounded-2xl bg-[#faf6ef] p-4 text-sm md:grid-cols-2"><p className="flex gap-2"><MapPin size={17} className="text-[#bd4a36]"/>{item.venue.name} · {item.venue.address}</p><p className="flex gap-2"><ShieldCheck size={17} className="text-[#bd4a36]"/>平台统一预约与核销</p></div>{item.description&&<div className="mt-7"><h2 className="font-semibold">项目介绍</h2><p className="mt-2 whitespace-pre-line leading-7 text-slate-600">{item.description}</p></div>}{item.notice&&<div className="mt-7"><h2 className="font-semibold">预约须知</h2><p className="mt-2 whitespace-pre-line leading-7 text-slate-600">{item.notice}</p></div>}</div></section>
      <aside className="h-fit rounded-3xl border border-[#e6ddd0] bg-white p-6 shadow-sm lg:sticky lg:top-6"><h2 className="font-serif text-2xl">选择预约时段</h2><div className="mt-4 space-y-2">{item.slots.map(slot=><button key={slot.id} disabled={slot.remaining<1} onClick={()=>setSlotId(slot.id)} className={`w-full rounded-xl border p-3 text-left ${slotId===slot.id?"border-[#bc4032] bg-[#fff6f3]":"border-slate-200"} disabled:opacity-40`}><div className="flex justify-between text-sm font-medium"><span><Clock3 size={15} className="mr-1 inline"/>{new Date(slot.startAt).toLocaleString("zh-CN",{month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"})}</span><span className="text-[#b83c2f]">余 {slot.remaining}</span></div><p className="mt-1 text-xs text-slate-500"><Users size={13} className="mr-1 inline"/>{slot.crowd.label}</p></button>)}</div><label className="mt-4 block text-sm">预约人数<input type="number" min={1} max={10} value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3"/></label><label className="mt-3 block text-sm">预约人<input value={contactName} onChange={e=>setContactName(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" placeholder="请输入姓名"/></label><label className="mt-3 block text-sm">手机号<input value={contactPhone} onChange={e=>setContactPhone(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-slate-200 px-3" placeholder="用于接收预约信息"/></label>{message&&<p className="mt-3 text-sm text-red-600">{message}</p>}<button onClick={submit} disabled={!slotId||submitting} className="mt-5 h-12 w-full rounded-xl bg-[#b9342b] font-semibold text-white disabled:opacity-50">{submitting?"提交中…":"确认预约（无需支付）"}</button><p className="mt-3 text-center text-xs text-slate-400">预约成功后凭 6 位核销码入场</p></aside></div></div></main>;
}
