"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { CalendarCheck2, MapPin } from "lucide-react";

type Booking={id:string;bookingNo:string;verifyCode:string;quantity:number;status:string;contactName:string;slot:{startAt:string;ticketItem:{title:string;venue:{name:string;address:string}}}};
const statusText:Record<string,string>={CONFIRMED:"待使用",VERIFIED:"已核销",CANCELLED:"已取消",EXPIRED:"已过期"};
export default function MyBookingsPage(){const [items,setItems]=useState<Booking[]>([]);const [loading,setLoading]=useState(true);async function load(){setLoading(true);const r=await fetch("/api/bookings").then(r=>r.json());setItems(r.data??[]);setLoading(false)}useEffect(()=>{fetch("/api/bookings").then(r=>r.json()).then(r=>setItems(r.data??[])).finally(()=>setLoading(false))},[]);async function cancel(id:string){if(!confirm("确定取消这个预约吗？"))return;await fetch(`/api/bookings/${id}`,{method:"PATCH"});await load()}
return <div><div className="mb-6 flex items-end justify-between"><div><h1 className="font-serif text-3xl">我的票务预约</h1><p className="mt-2 text-sm text-slate-500">查看核销码与预约状态，到场后向工作人员出示。</p></div><Link href="/tickets" className="text-sm text-[#bd3c30]">继续预约</Link></div>{loading?<p className="py-16 text-center text-slate-400">加载中…</p>:<div className="space-y-4">{items.map(b=><article key={b.id} className="rounded-2xl border border-[#eadfd7] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-slate-400">预约单 {b.bookingNo}</p><h2 className="mt-2 text-lg font-semibold">{b.slot.ticketItem.title}</h2><p className="mt-2 text-sm text-slate-500"><MapPin size={14} className="mr-1 inline"/>{b.slot.ticketItem.venue.name}</p><p className="mt-1 text-sm text-slate-500"><CalendarCheck2 size={14} className="mr-1 inline"/>{new Date(b.slot.startAt).toLocaleString("zh-CN")} · {b.quantity} 人</p></div><div className="text-right"><span className="rounded-full bg-[#f7e8e3] px-3 py-1 text-xs text-[#b6392e]">{statusText[b.status]??b.status}</span>{b.status==="CONFIRMED"&&<div className="mt-3 rounded-xl bg-[#25332f] px-5 py-3 text-white"><p className="text-[10px] tracking-widest text-white/60">核销码</p><b className="text-2xl tracking-[.2em]">{b.verifyCode}</b></div>}{b.status==="CONFIRMED"&&<button onClick={()=>cancel(b.id)} className="mt-3 text-xs text-slate-500 underline">取消预约</button>}</div></div></article>)}{items.length===0&&<div className="rounded-2xl border border-dashed bg-white py-20 text-center text-slate-400">还没有票务预约</div>}</div>}</div>}
